# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: validador.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'validador.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fvalidador.proto\x12\tvalidador\"*\n\nRequisicao\x12\x0c\n\x04tipo\x18\x01 \x01(\t\x12\x0e\n\x06numero\x18\x02 \x01(\t\",\n\x08Resposta\x12\x0e\n\x06valido\x18\x01 \x01(\x08\x12\x10\n\x08mensagem\x18\x02 \x01(\t2L\n\x12VerificarDocumento\x12\x36\n\x08Verifica\x12\x15.validador.Requisicao\x1a\x13.validador.Respostab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'validador_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUISICAO']._serialized_start=30
  _globals['_REQUISICAO']._serialized_end=72
  _globals['_RESPOSTA']._serialized_start=74
  _globals['_RESPOSTA']._serialized_end=118
  _globals['_VERIFICARDOCUMENTO']._serialized_start=120
  _globals['_VERIFICARDOCUMENTO']._serialized_end=196
# @@protoc_insertion_point(module_scope)
