// Code generated by gowsdl DO NOT EDIT.

package main

import (
	"context"
	"encoding/xml"
	"github.com/hooklift/gowsdl/soap"
	"time"
)

// against "unused imports"
var _ time.Time
var _ xml.Name

type AnyType struct {
	InnerXML string `xml:",innerxml"`
}

type AnyURI string

type NCName string

type Valida_cnpj struct {
	XMLName xml.Name `xml:"http://validator.example.com/ valida_cnpj"`

	Cnpj *string `xml:"cnpj,omitempty" json:"cnpj,omitempty"`
}

type Valida_cnpjResponse struct {
	XMLName xml.Name `xml:"http://validator.example.com/ valida_cnpjResponse"`

	Valida_cnpjResult *bool `xml:"valida_cnpjResult,omitempty" json:"valida_cnpjResult,omitempty"`
}

type Valida_cpf struct {
	XMLName xml.Name `xml:"http://validator.example.com/ valida_cpf"`

	Cpf *string `xml:"cpf,omitempty" json:"cpf,omitempty"`
}

type Valida_cpfResponse struct {
	XMLName xml.Name `xml:"http://validator.example.com/ valida_cpfResponse"`

	Valida_cpfResult *bool `xml:"valida_cpfResult,omitempty" json:"valida_cpfResult,omitempty"`
}

type Application interface {
	Valida_cpf(request *Valida_cpf) (*Valida_cpfResponse, error)

	Valida_cpfContext(ctx context.Context, request *Valida_cpf) (*Valida_cpfResponse, error)

	Valida_cnpj(request *Valida_cnpj) (*Valida_cnpjResponse, error)

	Valida_cnpjContext(ctx context.Context, request *Valida_cnpj) (*Valida_cnpjResponse, error)
}

type application struct {
	client *soap.Client
}

func NewApplication(client *soap.Client) Application {
	return &application{
		client: client,
	}
}

func (service *application) Valida_cpfContext(ctx context.Context, request *Valida_cpf) (*Valida_cpfResponse, error) {
	response := new(Valida_cpfResponse)
	err := service.client.CallContext(ctx, "valida_cpf", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *application) Valida_cpf(request *Valida_cpf) (*Valida_cpfResponse, error) {
	return service.Valida_cpfContext(
		context.Background(),
		request,
	)
}

func (service *application) Valida_cnpjContext(ctx context.Context, request *Valida_cnpj) (*Valida_cnpjResponse, error) {
	response := new(Valida_cnpjResponse)
	err := service.client.CallContext(ctx, "valida_cnpj", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *application) Valida_cnpj(request *Valida_cnpj) (*Valida_cnpjResponse, error) {
	return service.Valida_cnpjContext(
		context.Background(),
		request,
	)
}
